### ISSUE TITLE
Links da seção projetos

### ISSUE THREAD

**Issue by ghost** [fossfactory/wp-a19-theme#11]
Na seção Projetos na home, incluir o link dos sites dos projetos.

**Comment by gusgustavo** [comment]
Links da seção:
- http://livreacesso.net/
- http://violacoes.artigo19.org
- http://artigo19.org/centro
- http://artigo19.org/liberdadedigital

**Comment by ElvisBM** [comment]
Adicionar um campo personalizado chamado "link" com o conteudo
