### ISSUE TITLE
Imagens dos artigos não centralizam

### ISSUE THREAD

**Issue by gusgustavo** [fossfactory/wp-a19-theme#16]
As imagens nos posts não estão obedecendo o alinhamento feito dentro do post.

**Comment by ElvisBM** [comment]
Dentro do CSS, não tem nada de css para a imagem, fiz um teste com dentro do post colocando para ficar do lado direito e esquerdo e está funcionando sim a edição no post da imagem.

**Comment by gusgustavo** [comment]
Testei aqui e o alinhamento esquerda/direita funciona, mas não a centralização da imagem

**Comment by Quijaua** [comment]
feito! #169bcff
