### ISSUE TITLE
Critérios das notícias relacionadas

### ISSUE THREAD

**Issue by gusgustavo** [fossfactory/wp-a19-theme#17]
Quais são os critérios paras as notícias relacionadas nos artigos?

**Comment by ElvisBM** [comment]
O critério é da mesma categoria e os 4 ultimos post excluindo o post principal dá página

**Comment by Quijaua** [comment]
está pegando os posts de uma tag e o problema é quando o post está com várias tags. então limitei a quantidade de 4 e deixei randômica para todas as tags marcadas. a cada visita no post muda os posts relacionados #e0cf236
