### ISSUE TITLE
Criar Campo Pesonalizado

### ISSUE THREAD

**Issue by ElvisBM** [fossfactory/wp-a19-theme#20]
Criar Campo personalizado dentro do admin  > posts,  chamado "link"  para adicionar os links da sessão projeto

**Comment by gusgustavo** [comment]
Anotação:
livre acesso: http://livreacesso.net
centro: artigo19.org/centro
violações: violacoes.artigo19.org
liberdade digital: artigo19.org/liberdadedigital
