### ISSUE TITLE
Mapa do Site: “Centro de Referência” e “Direitos Digitais”

### ISSUE THREAD

**Issue by gusgustavo** [fossfactory/wp-a19-theme#41]
Os links para “Centro de Referência” e “Direitos Digitais” no mapa do site estão errados

**Comment by gusgustavo** [comment]
Corrigidos.
Remover o link Projetos da seção Mapa do Site.

**Comment by Quijaua** [comment]
removido o link projetos e corrigido o endereço de Centro de Referencias e Direitos Digitais (diretamente no painel do WordPress)
