### ISSUE TITLE
Mudança na coluna da direita

### ISSUE THREAD

**Issue by gusgustavo** [fossfactory/wp-a19-theme#43]
A coluna da direita ficaria no seguinte padrão:

  1) Últimas notícias
  2) Publicações
  3) Arte da ARTIGO 19 TV
  4) Os 2 Banners de denúncia

Exceção 1: Na seção Notícias, a coluna da direita não deve ter o espaço
“Últimas Notícias”

Exceção 2: Na seção Publicações, a coluna da direita não deve ter o
espaço “Publicações”

Exceção 3: Na seção ARTIGO 19 TV, a coluna da direita não deve ter o
espaço “ARTIGO 19 na TV”

Exceção 4: Na seção de denúncia de casos de acesso à informação, tirar
da coluna da direita os banners de denúncia

**Comment by Quijaua** [comment]
feito!  #05760e4
